version: "3"
services:
  database:
    image: postgres
    container_name: database
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${PORT}:4000
    command: ${START_COMMAND}
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: database
    depends_on:
      - database
